package com.omariskandarani.livelatexapp

/** Built-in punctuation and common LaTeX fragments for the Leestekens palette (Community + Pro). */
object PunctuationDefaults {
    val ENTRIES: List<Pair<String, String>> = listOf(
        // Basic LaTeX / math
        "$…$" to "$",
        "\\" to "\\",
        "{ }" to "{}",
        "[ ]" to "[]",
        "( )" to "()",
        "^" to "^",
        "_" to "_",
        "\\&" to "&",
        "\\%" to "\\%",
        "\\#" to "\\#",
        "\\$" to "\\$",
        "\\_" to "\\_",
        "\\{" to "\\{",
        "\\}" to "\\}",
        "~" to "\\textasciitilde{}",
        "\\^" to "\\textasciicircum{}",
        // Dashes / dots
        "-" to "-",
        "– en-dash" to "--",
        "— em-dash" to "---",
        "…" to "\\ldots{}",
        "⋯" to "\\cdots{}",
        "⋮" to "\\vdots{}",
        "·" to "\\cdot{}",
        // Quotes NL/EN
        "`` ''" to "``",
        "` '" to "`",
        "“ ”" to "``",
        "‘ ’" to "`",
        "« »" to "\\guillemotleft{}\\guillemotright{}",
        "„" to ",,",
        // Spaces
        "~" to "~",
        "\\," to "\\,",
        "\\:" to "\\:",
        "\\;" to "\\;",
        "quad" to "\\quad{}",
        "qquad" to "\\qquad{}",
        "\\!" to "\\!",
        // Common symbols
        "§" to "\\S{}",
        "¶" to "\\P{}",
        "©" to "\\copyright{}",
        "®" to "\\textregistered{}",
        "™" to "\\texttrademark{}",
        "°" to "\\textdegree{}",
        "′" to "\\prime{}",
        "″" to "\\prime\\prime{}",
        "∞" to "\\infty{}",
        "±" to "\\pm{}",
        "∓" to "\\mp{}",
        "×" to "\\times{}",
        "÷" to "\\div{}",
        "√" to "\\sqrt{}",
        "∑" to "\\sum{}",
        "∏" to "\\prod{}",
        "∫" to "\\int{}",
        "∂" to "\\partial{}",
        "∇" to "\\nabla{}",
        "∀" to "\\forall{}",
        "∃" to "\\exists{}",
        "∈" to "\\in{}",
        "∉" to "\\notin{}",
        "⊂" to "\\subset{}",
        "⊆" to "\\subseteq{}",
        "∪" to "\\cup{}",
        "∩" to "\\cap{}",
        "∅" to "\\emptyset{}",
        "∧" to "\\wedge{}",
        "∨" to "\\vee{}",
        "¬" to "\\neg{}",
        "→" to "\\rightarrow{}",
        "⇒" to "\\Rightarrow{}",
        "↔" to "\\leftrightarrow{}",
        "↦" to "\\mapsto{}",
        "α" to "\\alpha{}",
        "β" to "\\beta{}",
        "γ" to "\\gamma{}",
        "δ" to "\\delta{}",
        "ε" to "\\varepsilon{}",
        "θ" to "\\theta{}",
        "λ" to "\\lambda{}",
        "μ" to "\\mu{}",
        "π" to "\\pi{}",
        "σ" to "\\sigma{}",
        "φ" to "\\varphi{}",
        "ω" to "\\omega{}",
        "Γ" to "\\Gamma{}",
        "Δ" to "\\Delta{}",
        "Θ" to "\\Theta{}",
        "Λ" to "\\Lambda{}",
        "Σ" to "\\Sigma{}",
        "Ω" to "\\Omega{}",
        "≤" to "\\leq{}",
        "≥" to "\\geq{}",
        "≠" to "\\neq{}",
        "≈" to "\\approx{}",
        "≡" to "\\equiv{}",
        "∼" to "\\sim{}",
        "⊥" to "\\perp{}",
        "∥" to "\\parallel{}",
        "½" to "\\frac{1}{2}",
        "¼" to "\\frac{1}{4}",
        "¾" to "\\frac{3}{4}",
        "\\frac{}{}" to "\\frac{}{}",
        "\\sqrt{}" to "\\sqrt{}",
        "begin/end" to "\\begin{}\n\n\\end{}",
        "\\item" to "\\item ",
        "\\hline" to "\\hline",
        "ij" to "ij",
        "IJ" to "IJ",
        "€" to "\\euro{}",
        "£" to "\\pounds{}",
        "¥" to "\\textyen{}",
        "¢" to "\\textcent{}"
    )
}
